### ISSUE TITLE
Need to activate after every restart

### ISSUE THREAD

**Issue by rZiMiZ** [Jaggernaut555/midi-mixer-voicemeeter#7]
Hiho, every time i restart the pc, i need to click activate the plugin, previosly i was using the discord plugin, and dont needed to manual activate... any idea why i have this issue on voicemeeter plugin? :(

**Comment by Jaggernaut555** [comment]
It may be the issue in #4 about application startup order. e.g. voicemeeter starts AFTER midi mixer and the plugin couldn't contact it so it turned off.

If you're on a version less than v1.3.2 you'll need to update to [the latest version](https://github.com/Jaggernaut555/midi-mixer-voicemeeter/releases) where that problem was fixed.

If you are on a version newer than that it's something else and I might need to ask for some debug information so I can fix it.

**Comment by rZiMiZ** [comment]
Humm, understanded, thanks, i will delay the midimixer on startup!! :)

So, other thing, i see you put in settings "max db." option, can u add "min db." option? because for my use (tv) the -27+- to -60db is irrelevant... so i loss precision on my phisical fader because i just use like 50% (-25db[50%-+] to +12db[100%])

Oh, also, very thanks for the previously help! :D

**Comment by Jaggernaut555** [comment]
With the newer version you shouldn't have to alter the application startup order. The plugin shouldn't turn off and will occasionally check if voicemeeter has launched and it can connect.

I've created issue #8 for the min db feature request. That should be fairly simply to add.
